apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.getTask.Name }}-todo-get-task-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.getTask.Name }}-todo-get-task-api
  ports:
    - port: {{ .Values.getTask.ServicePort }}
      targetPort: {{ .Values.getTask.port }}
