apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deleteTask.Name }}-todo-delete-tasks-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deleteTask.Name }}-todo-delete-tasks-api
  ports:
    - port: {{ .Values.deleteTask.ServicePort }}
      targetPort: {{ .Values.deleteTask.port }}
