apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.Name }}-todo-ui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.ui.Name }}-todo-ui
  ports:
    - port: {{ .Values.ui.ServicePort }}
      targetPort: {{ .Values.ui.port }}
